@Invinsense.Server_HostAddress = http://localhost:5197

GET {{Invinsense.Server_HostAddress}}/
Accept: application/json

###

GET {{Invinsense.Server_HostAddress}}/tools/osquery/
Accept: application/json


